name: Linting with Pylint
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Checks with pylint
    steps:

    - name: Install dependencies
      run: sudo apt-get install libgirepository1.0-dev

    - name: Checkout branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v35
      with:
        files: "**/*.py"

    - name: Install python
      if: steps.chaged-files.output.any_changed == 'true'
      uses: actions/setup-python@v3
      with:
        python-version: 3.x


    - run: pip install --upgrade pip
      if: steps.chaged-files.output.any_changed == 'true'
    - run: pip install .
      if: steps.chaged-files.output.any_changed == 'true'
    - run: pip install pylint==2.16.*
      if: steps.chaged-files.output.any_changed == 'true'
    - run: pylint --rcfile=pylintrc ${{ steps.changed-files.outputs.all_changed_files }}
      if: steps.chaged-files.output.any_changed == 'true'
